[env:adafruit_feather_esp32_v2]
platform = espressif32
board = adafruit_feather_esp32_v2
framework = arduino
monitor_speed = 115200

extra_scripts = pre:scripts/gen_version.py

lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.2
    Preferences
